// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcgxlzxwxpyjsvijomdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZ3hsenh3eHB5anN2aWpvbWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDU0MzcsImV4cCI6MjA2NTMyMTQzN30.mE9Ni3t85-f9na8TMN2y6AQ_ELFsqJq8VkQHg5Pc4QA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);